# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/toolkit/tools"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
