// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package imagecustomizerlib

import (
	"fmt"
	"slices"
	"strings"

	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/grub"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/logger"
)

var (
	ErrAclUkiAddonSplit = NewImageCustomizerError("AclUkiAddon:Split",
		"failed to split kernel command line into ACL UKI addons")
	ErrAclUkiAddonEmptyPersistentCmdline = NewImageCustomizerError("AclUkiAddon:EmptyPersistentCmdline",
		"kernel command line has no persistent arguments")
)

const (
	// The kernel argument that makes ACL run its first-boot provisioning.
	aclFirstBootArg = "flatcar.first_boot=detected"

	// Name of the transient addon that carries only aclFirstBootArg.
	aclFirstBootAddonName = "firstboot.addon.efi"

	// aclOemAddonName is the name of ACL's native "oem" addon file, holding whatever cmdline
	// arguments remain once the first-boot and dm-verity arguments have been split out. This
	// matches the file name a stock (non-customized) ACL image already uses natively (see
	// aclVerityAddonTemplatesDir and a stock image's efi/Linux/*.efi.extra.d), so Image
	// Customizer's generated UKI addon layout is structurally identical to a native ACL image's
	// layout, instead of introducing an IC-specific "vmlinuz-<kernel>.addon.efi" bundle that a
	// stock ACL image never has.
	aclOemAddonName = "oem.addon.efi"

	// aclVerityAddonName is the name of ACL's live dm-verity addon file. Trident regenerates this
	// file per A/B slot (see aclVerityAddonTemplatesDir's doc comment above) independently of
	// Image Customizer, so Image Customizer must never fold dm-verity arguments into any other
	// addon file: systemd-boot loads addons in filename-alphabetical order, and if verity
	// arguments end up duplicated into another addon file that loads after this one on the
	// cmdline, that stale duplicate wins (last-value-wins), breaking AB-update boot.
	aclVerityAddonName = "verity.addon.efi"
)

// aclVerityCmdlineArgNames lists every kernel argument name that identifies /usr dm-verity
// configuration (device locators, root hash digest, and options) rather than general OS
// configuration. These must always be isolated into their own addon file (aclVerityAddonName) --
// never folded into aclOemAddonName or any IC-generated bundle -- because they are per-A/B-slot
// and are independently regenerated by Trident (see aclVerityAddonName's doc comment).
var aclVerityCmdlineArgNames = []string{
	"systemd.verity_usr_data",
	"systemd.verity_usr_hash",
	"systemd.verity_usr_options",
	"usrhash",
	"rd.systemd.verity",
}

// aclGetUkiAddonSpecs returns ACL's native cmdline addon layout, matching a stock (non-customized)
// ACL image's ESP structure: up to three discrete addon files, none of which bundle every
// non-first-boot argument together:
//   - aclFirstBootAddonName, holding only aclFirstBootArg (omitted once first-boot has completed),
//   - aclVerityAddonName, holding every dm-verity argument (see aclVerityCmdlineArgNames; omitted
//     if cmdline carries none),
//   - aclOemAddonName, holding every other remaining argument (e.g. flatcar.oem.id=, console=,
//     mount.usr=, root=).
//
// This deliberately never produces a "vmlinuz-<kernel>.addon.efi" persistent bundle: folding
// dm-verity arguments into any addon other than aclVerityAddonName lets a stale copy of those
// arguments outlive and (due to alphabetical addon load order) override a freshly-written,
// per-A/B-slot aclVerityAddonName written later by Trident, breaking AB-update boot for ACL-T
// images.
func aclGetUkiAddonSpecs(kernel string, cmdline string) ([]UkiAddonSpec, error) {
	remainingCmdline, hasFirstBootArg, err := aclStripFirstBootArg(cmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	oemCmdline, verityCmdline, err := aclSplitVerityArgs(remainingCmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	if oemCmdline == "" && verityCmdline == "" {
		return nil, fmt.Errorf("%w (kernel='%s', cmdline='%s')", ErrAclUkiAddonEmptyPersistentCmdline, kernel, cmdline)
	}

	specs := []UkiAddonSpec(nil)
	if oemCmdline != "" {
		specs = append(specs, UkiAddonSpec{FileName: aclOemAddonName, Cmdline: oemCmdline})
	}
	if verityCmdline != "" {
		specs = append(specs, UkiAddonSpec{FileName: aclVerityAddonName, Cmdline: verityCmdline})
	}

	if !hasFirstBootArg {
		logger.Log.Infof("Kernel (%s) command line has no (%s); not adding a first-boot addon", kernel,
			aclFirstBootArg)
		return specs, nil
	}

	specs = append(specs, UkiAddonSpec{
		FileName: aclFirstBootAddonName,
		Cmdline:  aclFirstBootArg,
	})
	return specs, nil
}

// aclSplitVerityArgs separates cmdline's dm-verity arguments (aclVerityCmdlineArgNames) from every
// other argument, returning (oemCmdline, verityCmdline). Either return value may be empty if
// cmdline has no arguments of that kind.
func aclSplitVerityArgs(cmdline string) (string, string, error) {
	tokens, err := grub.TokenizeConfig(cmdline)
	if err != nil {
		return "", "", fmt.Errorf("failed to tokenize kernel command line:\n%w", err)
	}

	args, err := ParseCommandLineArgs(tokens)
	if err != nil {
		return "", "", fmt.Errorf("failed to parse kernel command-line args:\n%w", err)
	}

	oemArgs := []string(nil)
	verityArgs := []string(nil)
	for _, arg := range args {
		if arg.ValueHasVarExpansion {
			// The parsed form of an arg with a variable expansion is truncated at the expansion, so
			// the arg cannot be rewritten faithfully.
			return "", "", fmt.Errorf("kernel command-line arg (%s) contains a variable expansion", arg.Arg)
		}

		if slices.Contains(aclVerityCmdlineArgNames, arg.Name) {
			verityArgs = append(verityArgs, arg.Arg)
			continue
		}

		oemArgs = append(oemArgs, arg.Arg)
	}

	return GrubArgsToString(oemArgs), GrubArgsToString(verityArgs), nil
}

// aclGetUkiAddonSpecsPreserving splits cmdline across ACL's native first-boot/oem/verity addons
// (same rules as aclGetUkiAddonSpecs), and additionally passes through, untouched, every OTHER
// addon file that already exists for this kernel (e.g. fips.addon.efi, kdump.addon.efi, or a
// verity.addon.efi already regenerated by Trident for the live A/B slot) instead of folding their
// arguments into a generated addon.
//
// This matters most for dm-verity: ACL's per-slot verity.addon.efi is regenerated by Trident
// independently of Image Customizer, using alphabetical addon load order (systemd-boot loads
// "verity.addon.efi" before "vmlinuz-*.addon.efi"). If Image Customizer folds a stale copy of the
// verity arguments into another addon instead of leaving verity.addon.efi as its own file, that
// stale copy loads AFTER (and so overrides) a freshly-written verity.addon.efi, breaking boot.
// Preserving every non-managed addon file as its own file sidesteps this regardless of which
// addons ACL adds in the future, without Image Customizer needing to know about them individually.
//
// existingAddons is nil when there's no known prior addon-file structure to preserve (e.g. this is
// a new kernel installed during customization); in that case this falls back to
// aclGetUkiAddonSpecs, splitting cmdline as a single flat string as before.
func aclGetUkiAddonSpecsPreserving(kernel string, cmdline string, existingAddons map[string]string) ([]UkiAddonSpec, error) {
	if len(existingAddons) == 0 {
		return aclGetUkiAddonSpecs(kernel, cmdline)
	}

	// The addon files ACL's own first-boot/oem split manages. ukiAddonFileName(kernel) (the old
	// IC-generated "vmlinuz-<kernel>.addon.efi" persistent bundle) is included here too so that an
	// image built by an older Image Customizer version self-heals back into the native layout on
	// its next customization pass, instead of that legacy file lingering forever. Every other
	// existing addon file name -- including verity.addon.efi -- is preserved untouched.
	managedFileNames := map[string]bool{
		ukiMainCmdlineAddonKey:   true,
		ukiAddonFileName(kernel): true,
		aclOemAddonName:          true,
		aclFirstBootAddonName:    true,
	}

	managedFileNamesFound := []string(nil)
	passthroughSpecs := []UkiAddonSpec(nil)
	for fileName := range existingAddons {
		if managedFileNames[fileName] {
			managedFileNamesFound = append(managedFileNamesFound, fileName)
			continue
		}
		passthroughSpecs = append(passthroughSpecs, UkiAddonSpec{FileName: fileName, Cmdline: existingAddons[fileName]})
	}
	// Sort so the joined managed cmdline (and therefore the resulting split) is deterministic
	// regardless of Go's randomized map iteration order.
	slices.Sort(managedFileNamesFound)

	managedParts := make([]string, 0, len(managedFileNamesFound))
	for _, fileName := range managedFileNamesFound {
		managedParts = append(managedParts, existingAddons[fileName])
	}

	specs, err := aclGetUkiAddonSpecs(kernel, strings.Join(managedParts, " "))
	if err != nil {
		return nil, err
	}

	specs = append(specs, passthroughSpecs...)
	slices.SortFunc(specs, func(a, b UkiAddonSpec) int { return strings.Compare(a.FileName, b.FileName) })

	return specs, nil
}

// aclStripFirstBootArg removes every occurrence of aclFirstBootArg from cmdline and reports
// whether any was present.
func aclStripFirstBootArg(cmdline string) (string, bool, error) {
	tokens, err := grub.TokenizeConfig(cmdline)
	if err != nil {
		return "", false, fmt.Errorf("failed to tokenize kernel command line:\n%w", err)
	}

	args, err := ParseCommandLineArgs(tokens)
	if err != nil {
		return "", false, fmt.Errorf("failed to parse kernel command-line args:\n%w", err)
	}

	hasFirstBootArg := false
	persistentArgs := []string(nil)
	for _, arg := range args {
		if arg.ValueHasVarExpansion {
			// The parsed form of an arg with a variable expansion is truncated at the expansion, so
			// the arg cannot be rewritten faithfully.
			return "", false, fmt.Errorf("kernel command-line arg (%s) contains a variable expansion", arg.Arg)
		}

		if arg.Arg == aclFirstBootArg {
			hasFirstBootArg = true
			continue
		}

		persistentArgs = append(persistentArgs, arg.Arg)
	}

	return GrubArgsToString(persistentArgs), hasFirstBootArg, nil
}
