// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package imagecustomizerlib

import (
	"fmt"
	"slices"
	"strings"

	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/grub"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/logger"
)

var (
	ErrAclUkiAddonSplit = NewImageCustomizerError("AclUkiAddon:Split",
		"failed to split kernel command line into ACL UKI addons")
	ErrAclUkiAddonEmptyPersistentCmdline = NewImageCustomizerError("AclUkiAddon:EmptyPersistentCmdline",
		"kernel command line has no persistent arguments")
)

const (
	// The kernel argument that makes ACL run its first-boot provisioning.
	aclFirstBootArg = "flatcar.first_boot=detected"

	// Name of the transient addon that carries only aclFirstBootArg.
	aclFirstBootAddonName = "firstboot.addon.efi"
)

// aclGetUkiAddonSpecs returns ACL's cmdline addon layout: a persistent <kernel>.addon.efi holding
// every argument except aclFirstBootArg, plus a transient firstboot.addon.efi holding exactly that
// argument. If the command line does not contain the argument, the image has already completed its
// first boot and only the persistent addon spec is returned.
func aclGetUkiAddonSpecs(kernel string, cmdline string) ([]UkiAddonSpec, error) {
	persistentCmdline, hasFirstBootArg, err := aclStripFirstBootArg(cmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	if persistentCmdline == "" {
		return nil, fmt.Errorf("%w (kernel='%s', cmdline='%s')", ErrAclUkiAddonEmptyPersistentCmdline, kernel, cmdline)
	}

	specs := []UkiAddonSpec{
		{FileName: ukiAddonFileName(kernel), Cmdline: persistentCmdline},
	}

	if !hasFirstBootArg {
		logger.Log.Infof("Kernel (%s) command line has no (%s); not adding a first-boot addon", kernel,
			aclFirstBootArg)
		return specs, nil
	}

	specs = append(specs, UkiAddonSpec{
		FileName: aclFirstBootAddonName,
		Cmdline:  aclFirstBootArg,
	})
	return specs, nil
}

// aclGetUkiAddonSpecsPreserving splits cmdline across ACL's persistent and first-boot addons (same
// rules as aclGetUkiAddonSpecs), and additionally passes through, untouched, every OTHER addon
// file that already exists for this kernel (e.g. oem.addon.efi, verity.addon.efi,
// fips.addon.efi, kdump.addon.efi) instead of folding their arguments into the persistent addon.
//
// This matters most for dm-verity: ACL's per-slot verity.addon.efi is regenerated by Trident
// independently of Image Customizer, using alphabetical addon load order (systemd-boot loads
// "verity.addon.efi" before "vmlinuz-*.addon.efi"). If Image Customizer folds a stale copy of the
// verity arguments into the persistent addon instead of leaving verity.addon.efi as its own file,
// that stale copy loads AFTER (and so overrides) a freshly-written verity.addon.efi, breaking boot.
// Preserving every non-managed addon file as its own file sidesteps this regardless of which
// addons ACL adds in the future, without Image Customizer needing to know about them individually.
//
// existingAddons is nil when there's no known prior addon-file structure to preserve (e.g. this is
// a new kernel installed during customization); in that case this falls back to
// aclGetUkiAddonSpecs, splitting cmdline as a single flat string as before.
func aclGetUkiAddonSpecsPreserving(kernel string, cmdline string, existingAddons map[string]string) ([]UkiAddonSpec, error) {
	if len(existingAddons) == 0 {
		return aclGetUkiAddonSpecs(kernel, cmdline)
	}

	// The addon files ACL's own persistent/first-boot split manages. Every other existing addon
	// file name is preserved untouched.
	managedFileNames := map[string]bool{
		ukiMainCmdlineAddonKey:   true,
		ukiAddonFileName(kernel): true,
		aclFirstBootAddonName:    true,
	}

	managedParts := []string(nil)
	passthroughSpecs := []UkiAddonSpec(nil)
	for fileName, addonCmdline := range existingAddons {
		if managedFileNames[fileName] {
			managedParts = append(managedParts, addonCmdline)
			continue
		}
		passthroughSpecs = append(passthroughSpecs, UkiAddonSpec{FileName: fileName, Cmdline: addonCmdline})
	}

	specs, err := aclGetUkiAddonSpecs(kernel, strings.Join(managedParts, " "))
	if err != nil {
		return nil, err
	}

	specs = append(specs, passthroughSpecs...)
	slices.SortFunc(specs, func(a, b UkiAddonSpec) int { return strings.Compare(a.FileName, b.FileName) })

	return specs, nil
}

// aclStripFirstBootArg removes every occurrence of aclFirstBootArg from cmdline and reports
// whether any was present.
func aclStripFirstBootArg(cmdline string) (string, bool, error) {
	tokens, err := grub.TokenizeConfig(cmdline)
	if err != nil {
		return "", false, fmt.Errorf("failed to tokenize kernel command line:\n%w", err)
	}

	args, err := ParseCommandLineArgs(tokens)
	if err != nil {
		return "", false, fmt.Errorf("failed to parse kernel command-line args:\n%w", err)
	}

	hasFirstBootArg := false
	persistentArgs := []string(nil)
	for _, arg := range args {
		if arg.ValueHasVarExpansion {
			// The parsed form of an arg with a variable expansion is truncated at the expansion, so
			// the arg cannot be rewritten faithfully.
			return "", false, fmt.Errorf("kernel command-line arg (%s) contains a variable expansion", arg.Arg)
		}

		if arg.Arg == aclFirstBootArg {
			hasFirstBootArg = true
			continue
		}

		persistentArgs = append(persistentArgs, arg.Arg)
	}

	return GrubArgsToString(persistentArgs), hasFirstBootArg, nil
}
