// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package imagecustomizerlib

import (
	"fmt"
	"slices"
	"strings"

	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/grub"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/logger"
)

var (
	ErrAclUkiAddonSplit = NewImageCustomizerError("AclUkiAddon:Split",
		"failed to split kernel command line into ACL UKI addons")
	ErrAclUkiAddonEmptyPersistentCmdline = NewImageCustomizerError("AclUkiAddon:EmptyPersistentCmdline",
		"kernel command line has no persistent arguments")
)

const (
	// The kernel argument that makes ACL run its first-boot provisioning.
	aclFirstBootArg = "flatcar.first_boot=detected"

	// Name of the transient addon that carries only aclFirstBootArg.
	aclFirstBootAddonName = "firstboot.addon.efi"

	// aclOemAddonName is the name of ACL's native "oem" addon file, holding whatever cmdline
	// arguments remain once the first-boot and dm-verity arguments have been split out. This
	// matches the file name a stock (non-customized) ACL image already uses natively (see
	// aclVerityAddonTemplatesDir and a stock image's efi/Linux/*.efi.extra.d), so Image
	// Customizer's generated UKI addon layout is structurally identical to a native ACL image's
	// layout, instead of introducing an IC-specific "vmlinuz-<kernel>.addon.efi" bundle that a
	// stock ACL image never has. Only used when there's no existing addon structure to preserve
	// (see aclGetUkiAddonSpecs); once a kernel has existing addons, its oem.addon.efi -- like
	// every other addon file ACL didn't ask Image Customizer to manage -- is preserved untouched
	// (see aclGetUkiAddonSpecsPreserving).
	aclOemAddonName = "oem.addon.efi"

	// aclVerityAddonName is the name of ACL's live dm-verity addon file. Trident regenerates this
	// file's device-locator args per A/B slot (see aclVerityAddonTemplatesDir's doc comment in
	// aclverityaddontemplates.go) independently of Image Customizer; Image Customizer's own
	// responsibility for this file is limited to keeping its embedded /usr root hash in sync with
	// /usr's current content (see aclUpdateVerityAddonTemplates, which refreshes both this live
	// file and the per-slot templates). Image Customizer must never fold dm-verity arguments into
	// any other addon file: systemd-boot loads addons in filename-alphabetical order, and a stale
	// duplicate of these args in a different, later-loading file would win (last-value-wins),
	// breaking AB-update boot.
	aclVerityAddonName = "verity.addon.efi"

	// aclCustomizedAddonName is the addon file Image Customizer uses to carry any kernel
	// command-line arguments that user configuration (e.g. os.uki.kernelCommandLine) adds on top
	// of a kernel's existing addon structure. See aclGetUkiAddonSpecsPreserving for why these
	// arguments get their own dedicated file instead of being folded into an existing native ACL
	// addon file such as oem.addon.efi.
	aclCustomizedAddonName = "customized.addon.efi"
)

// aclVerityCmdlineArgNames lists every kernel argument name that identifies /usr dm-verity
// configuration (device locators, root hash digest, and options) rather than general OS
// configuration. These must always be isolated into their own addon file (aclVerityAddonName) --
// never folded into aclOemAddonName or aclCustomizedAddonName -- because they are per-A/B-slot and
// are independently regenerated by Trident and Image Customizer (see aclVerityAddonName's doc
// comment).
//
// This list was verified directly against a real ACL image's verity-a.addon.efi /
// verity-b.addon.efi / live verity.addon.efi content (branch-2 pipeline artifact): all three
// files carry exactly these four arguments, and nothing else. rd.systemd.verity is deliberately
// NOT included: it does not appear in any of those files (ACL's /usr dm-verity setup activates
// automatically off the presence of systemd.verity_usr_hash=, without needing an explicit enable
// flag), so treating it as verity-owned here would be speculative rather than evidence-based.
var aclVerityCmdlineArgNames = []string{
	"systemd.verity_usr_data",
	"systemd.verity_usr_hash",
	"systemd.verity_usr_options",
	"usrhash",
}

// aclParseCmdline tokenizes and parses cmdline into individual kernel command-line arguments,
// rejecting any argument whose value contains a variable expansion (e.g. $a) -- the parsed form of
// such an argument is truncated at the expansion, so it cannot be manipulated (split, deduplicated,
// or rewritten) faithfully.
func aclParseCmdline(cmdline string) ([]grubConfigLinuxArg, error) {
	tokens, err := grub.TokenizeConfig(cmdline)
	if err != nil {
		return nil, fmt.Errorf("failed to tokenize kernel command line:\n%w", err)
	}

	args, err := ParseCommandLineArgs(tokens)
	if err != nil {
		return nil, fmt.Errorf("failed to parse kernel command-line args:\n%w", err)
	}

	for _, arg := range args {
		if arg.ValueHasVarExpansion {
			return nil, fmt.Errorf("kernel command-line arg (%s) contains a variable expansion", arg.Arg)
		}
	}

	return args, nil
}

// aclGetUkiAddonSpecs returns ACL's native cmdline addon layout, matching a stock (non-customized)
// ACL image's ESP structure: up to three discrete addon files, none of which bundle every
// non-first-boot argument together:
//   - aclFirstBootAddonName, holding only aclFirstBootArg (omitted once first-boot has completed),
//   - aclVerityAddonName, holding every dm-verity argument (see aclVerityCmdlineArgNames; omitted
//     if cmdline carries none),
//   - aclOemAddonName, holding every other remaining argument (e.g. flatcar.oem.id=, console=,
//     mount.usr=, root=).
//
// This deliberately never produces a "vmlinuz-<kernel>.addon.efi" persistent bundle: folding
// dm-verity arguments into any addon other than aclVerityAddonName lets a stale copy of those
// arguments outlive and (due to alphabetical addon load order) override a freshly-written,
// per-A/B-slot aclVerityAddonName written later by Trident, breaking AB-update boot for ACL-T
// images.
//
// This is only used when there's no existing addon structure to preserve (a brand-new kernel
// installed during customization); see aclGetUkiAddonSpecsPreserving for the preserving case.
func aclGetUkiAddonSpecs(kernel string, cmdline string) ([]UkiAddonSpec, error) {
	remainingCmdline, hasFirstBootArg, err := aclStripFirstBootArg(cmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	oemCmdline, verityCmdline, err := aclSplitVerityArgs(remainingCmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	if oemCmdline == "" && verityCmdline == "" {
		return nil, fmt.Errorf("%w (kernel='%s', cmdline='%s')", ErrAclUkiAddonEmptyPersistentCmdline, kernel, cmdline)
	}

	specs := []UkiAddonSpec(nil)
	if oemCmdline != "" {
		specs = append(specs, UkiAddonSpec{FileName: aclOemAddonName, Cmdline: oemCmdline})
	}
	if verityCmdline != "" {
		specs = append(specs, UkiAddonSpec{FileName: aclVerityAddonName, Cmdline: verityCmdline})
	}

	if !hasFirstBootArg {
		logger.Log.Infof("Kernel (%s) command line has no (%s); not adding a first-boot addon", kernel,
			aclFirstBootArg)
		return specs, nil
	}

	specs = append(specs, UkiAddonSpec{
		FileName: aclFirstBootAddonName,
		Cmdline:  aclFirstBootArg,
	})
	return specs, nil
}

// aclSplitVerityArgs separates cmdline's dm-verity arguments (aclVerityCmdlineArgNames) from every
// other argument, returning (oemCmdline, verityCmdline). Either return value may be empty if
// cmdline has no arguments of that kind.
func aclSplitVerityArgs(cmdline string) (string, string, error) {
	args, err := aclParseCmdline(cmdline)
	if err != nil {
		return "", "", err
	}

	oemArgs := []string(nil)
	verityArgs := []string(nil)
	for _, arg := range args {
		if slices.Contains(aclVerityCmdlineArgNames, arg.Name) {
			verityArgs = append(verityArgs, arg.Arg)
			continue
		}

		oemArgs = append(oemArgs, arg.Arg)
	}

	return GrubArgsToString(oemArgs), GrubArgsToString(verityArgs), nil
}

// aclGetUkiAddonSpecsPreserving passes through every existing addon file for this kernel
// untouched -- including verity.addon.efi (Trident owns its device-locator args, and Image
// Customizer separately keeps its /usr root hash in sync via aclUpdateVerityAddonTemplates; see
// aclVerityAddonName's doc comment), oem.addon.efi, and any other file ACL or a future ACL version
// adds (fips.addon.efi, kdump.addon.efi, ...). Passing through by default means Image Customizer
// never needs to know about a new addon file ACL introduces for this to remain safe: an unknown
// file is preserved exactly as-is, rather than risking having its arguments folded into a
// generated bundle the way the pre-fix "vmlinuz-<kernel>.addon.efi" bundle did.
//
// Any kernel command-line argument in cmdline that user configuration added or changed relative to
// the existing addon structure (e.g. via os.uki.kernelCommandLine) is written to its own dedicated
// file, aclCustomizedAddonName, instead of being folded into an existing native addon file. This
// matters because systemd-boot loads addons in a fixed filename-alphabetical order and applies
// last-value-wins semantics for repeated arguments: writing a changed value into a different
// existing file could not reliably override (or be overridden by) that file depending on filename
// ordering. A new argument whose name doesn't collide with any existing addon file's arguments is
// simply appended to aclCustomizedAddonName. A new argument whose name DOES collide with an
// existing (non-customized) addon file's argument is rejected with an error: overriding a native
// ACL addon's argument isn't safely expressible under alphabetical load order, so surfacing this
// loudly is preferable to silently producing a config that may or may not take effect depending on
// filename sort order. A new dm-verity-named argument is silently ignored, since Trident and
// aclUpdateVerityAddonTemplates already own that data exclusively; kernel command-line
// customization is not a supported way to set it.
//
// existingAddons is nil/empty when there's no known prior addon-file structure to preserve (e.g.
// this is a new kernel installed during customization); in that case this falls back to
// aclGetUkiAddonSpecs, splitting cmdline as a single flat string.
func aclGetUkiAddonSpecsPreserving(kernel string, cmdline string, existingAddons map[string]string) ([]UkiAddonSpec, error) {
	if len(existingAddons) == 0 {
		return aclGetUkiAddonSpecs(kernel, cmdline)
	}

	cmdlineArgs, err := aclParseCmdline(cmdline)
	if err != nil {
		return nil, fmt.Errorf("%w:\n%w", ErrAclUkiAddonSplit, err)
	}

	// accountedFor holds every argument string already present in some existing addon file
	// (including the main UKI's own cmdline section, under ukiMainCmdlineAddonKey) -- these need
	// no action, since they're already covered by a passthrough spec below.
	accountedFor := map[string]bool{}
	// otherAddonArgNames holds every argument name already owned by an existing addon file OTHER
	// than aclCustomizedAddonName (including the main UKI's own cmdline section) -- used to detect
	// an unsupported override attempt.
	otherAddonArgNames := map[string]bool{}
	// customizedArgs holds aclCustomizedAddonName's own existing arguments (if the file already
	// exists), in order, so a new argument that updates one of these can replace it in place
	// instead of duplicating it.
	customizedArgs := []string(nil)
	customizedArgIndexByName := map[string]int{}

	passthroughSpecs := []UkiAddonSpec(nil)

	fileNames := make([]string, 0, len(existingAddons))
	for fileName := range existingAddons {
		fileNames = append(fileNames, fileName)
	}
	slices.Sort(fileNames) // deterministic order regardless of Go's randomized map iteration order

	for _, fileName := range fileNames {
		addonCmdline := existingAddons[fileName]

		args, err := aclParseCmdline(addonCmdline)
		if err != nil {
			return nil, fmt.Errorf("%w: existing addon (%s):\n%w", ErrAclUkiAddonSplit, fileName, err)
		}
		for _, arg := range args {
			accountedFor[arg.Arg] = true
		}

		switch fileName {
		case ukiMainCmdlineAddonKey:
			// The main UKI's own .cmdline section, not an addon file: nothing to pass through, but
			// its arguments still count for override detection below.
			for _, arg := range args {
				otherAddonArgNames[arg.Name] = true
			}

		case aclCustomizedAddonName:
			// Defer emitting this as a spec until any new/updated arguments have been merged in
			// below, so the file is only written once with its final combined content.
			for _, arg := range args {
				customizedArgs = append(customizedArgs, arg.Arg)
				customizedArgIndexByName[arg.Name] = len(customizedArgs) - 1
			}

		default:
			for _, arg := range args {
				otherAddonArgNames[arg.Name] = true
			}
			passthroughSpecs = append(passthroughSpecs, UkiAddonSpec{FileName: fileName, Cmdline: addonCmdline})
		}
	}

	for _, arg := range cmdlineArgs {
		if accountedFor[arg.Arg] {
			// Unchanged from what's already in some existing addon file (or the main UKI's own
			// cmdline); nothing to do.
			continue
		}

		if slices.Contains(aclVerityCmdlineArgNames, arg.Name) {
			logger.Log.Debugf("Ignoring new dm-verity kernel command-line arg (%s) for kernel (%s): "+
				"ACL's dm-verity addon is managed separately from kernel command-line customization",
				arg.Arg, kernel)
			continue
		}

		if idx, exists := customizedArgIndexByName[arg.Name]; exists {
			// Updates a value this kernel was previously customized with; replace in place.
			customizedArgs[idx] = arg.Arg
			continue
		}

		if otherAddonArgNames[arg.Name] {
			return nil, fmt.Errorf(
				"%w: kernel command-line arg (%s) for kernel (%s) would override an argument already "+
					"owned by an existing ACL UKI addon file; overriding an existing addon's argument is "+
					"not supported, since ACL addon files load in a fixed alphabetical order that cannot "+
					"guarantee the override takes effect",
				ErrAclUkiAddonSplit, arg.Arg, kernel)
		}

		customizedArgs = append(customizedArgs, arg.Arg)
		customizedArgIndexByName[arg.Name] = len(customizedArgs) - 1
	}

	if len(customizedArgs) > 0 {
		passthroughSpecs = append(passthroughSpecs,
			UkiAddonSpec{FileName: aclCustomizedAddonName, Cmdline: GrubArgsToString(customizedArgs)})
	}

	slices.SortFunc(passthroughSpecs, func(a, b UkiAddonSpec) int { return strings.Compare(a.FileName, b.FileName) })

	return passthroughSpecs, nil
}

// aclStripFirstBootArg removes every occurrence of aclFirstBootArg from cmdline and reports
// whether any was present.
func aclStripFirstBootArg(cmdline string) (string, bool, error) {
	args, err := aclParseCmdline(cmdline)
	if err != nil {
		return "", false, err
	}

	hasFirstBootArg := false
	persistentArgs := []string(nil)
	for _, arg := range args {
		if arg.Arg == aclFirstBootArg {
			hasFirstBootArg = true
			continue
		}

		persistentArgs = append(persistentArgs, arg.Arg)
	}

	return GrubArgsToString(persistentArgs), hasFirstBootArg, nil
}
