// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package imagecustomizerlib

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/imagecustomizerapi"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/imagegen/installutils"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/safechroot"
)

var (
	// Boot customization errors
	ErrBootGrubMkconfigGeneration = NewImageCustomizerError("Boot:GrubMkconfigGeneration", "failed to generate grub.cfg via grub2-mkconfig")
)

// BootConfigType represents the type of boot configuration used by the image.
type BootConfigType string

const (
	// BootConfigTypeGrubMkconfig indicates the image uses grub-mkconfig to generate grub.cfg.
	BootConfigTypeGrubMkconfig BootConfigType = "grub-mkconfig"
	// BootConfigTypeGrubLegacy indicates the image uses a manually maintained grub.cfg.
	BootConfigTypeGrubLegacy BootConfigType = "grub-legacy"
	// BootConfigTypeUki indicates the image uses UKI (Unified Kernel Image) without grub.cfg.
	BootConfigTypeUki BootConfigType = "uki"
)

type BootCustomizer struct {
	// The contents of the /boot/grub2/grub.cfg file.
	grubCfgContent string

	// The contents of the /etc/default/grub file.
	defaultGrubFileContent string

	// The type of boot configuration used by the image.
	bootConfigType BootConfigType
}

func NewBootCustomizer(imageChroot safechroot.ChrootInterface) (*BootCustomizer, error) {
	grubCfgContent, err := ReadGrub2ConfigFile(imageChroot)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}

	defaultGrubFileContent, err := readDefaultGrubFile(imageChroot)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}

	// Determine boot configuration type
	bootConfigType := determineBootConfigType(grubCfgContent, imageChroot)

	b := &BootCustomizer{
		grubCfgContent:         grubCfgContent,
		defaultGrubFileContent: defaultGrubFileContent,
		bootConfigType:         bootConfigType,
	}
	return b, nil
}

// determineBootConfigType detects the boot configuration type based on available files.
func determineBootConfigType(grubCfgContent string, imageChroot safechroot.ChrootInterface) BootConfigType {
	// If grub.cfg doesn't exist, check for UKI
	if grubCfgContent == "" {
		hasUkis, err := baseImageHasUkis(imageChroot.(*safechroot.Chroot))
		if err == nil && hasUkis {
			return BootConfigTypeUki
		}
		// No grub.cfg and no UKIs - default to grub-legacy (edge case)
		return BootConfigTypeGrubLegacy
	}

	// If grub.cfg exists, check if it's generated by grub-mkconfig
	if isGrubMkconfigConfig(grubCfgContent) {
		return BootConfigTypeGrubMkconfig
	}

	return BootConfigTypeGrubLegacy
}

// Returns whether or not the OS uses grub-mkconfig.
func (b *BootCustomizer) IsGrubMkconfigImage() bool {
	return b.bootConfigType == BootConfigTypeGrubMkconfig
}

// GetBootConfigType returns the type of boot configuration used by the image.
func (b *BootCustomizer) GetBootConfigType() BootConfigType {
	return b.bootConfigType
}

// Inserts new kernel command-line args into the grub config file.
func (b *BootCustomizer) AddKernelCommandLine(extraCommandLine []string) error {
	if len(extraCommandLine) <= 0 {
		return nil
	}

	combinedArgs := GrubArgsToString(extraCommandLine)

	if b.bootConfigType == BootConfigTypeGrubMkconfig {
		defaultGrubFileContent, err := addExtraCommandLineToDefaultGrubFile(b.defaultGrubFileContent, combinedArgs)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent
	} else if b.bootConfigType == BootConfigTypeGrubLegacy {
		// Add the args directly to the /boot/grub2/grub.cfg file.
		grubCfgContent, err := appendKernelCommandLineArgsAll(b.grubCfgContent, combinedArgs)
		if err != nil {
			return err
		}

		b.grubCfgContent = grubCfgContent
	}
	// For UKI, kernel command-line args are embedded in the UKI itself, not in grub config

	return nil
}

// getSELinuxModeFromGrub gets the image's configured SELinux mode from grub configuration.
// Returns (mode, found, error) where:
//   - mode: The detected SELinux mode (or SELinuxModeDefault if not found)
//   - found: true if grub config exists and was successfully parsed
//   - error: Any error encountered during parsing
func (b *BootCustomizer) getSELinuxModeFromGrub() (imagecustomizerapi.SELinuxMode, bool, error) {
	var err error
	var args []grubConfigLinuxArg

	// Get the SELinux kernel command-line args.
	if b.bootConfigType == BootConfigTypeGrubMkconfig {
		// Empty /etc/default/grub is valid, but means no SELinux config in grub
		if b.defaultGrubFileContent == "" {
			return imagecustomizerapi.SELinuxModeDefault, false, nil
		}

		// Check both GRUB_CMDLINE_LINUX and GRUB_CMDLINE_LINUX_DEFAULT variables
		// and merge arguments from both if they exist
		args, err = GetDefaultGrubFileLinuxArgsFromMultipleVars(b.defaultGrubFileContent)
		if err != nil {
			return imagecustomizerapi.SELinuxModeDefault, false, fmt.Errorf("failed to find SELinux args in grub file (%s):\n%w", installutils.GrubDefFile, err)
		}
	} else if b.bootConfigType == BootConfigTypeGrubLegacy {
		// Empty grub.cfg means no grub config available
		if b.grubCfgContent == "" {
			return imagecustomizerapi.SELinuxModeDefault, false, nil
		}

		args, _, err = getLinuxCommandLineArgs(b.grubCfgContent)
		if err != nil {
			return imagecustomizerapi.SELinuxModeDefault, false,
				fmt.Errorf("failed to parse SELinux args from grub file (%s):\n%w", installutils.GrubCfgFile, err)
		}
	} else {
		// BootConfigTypeUki - no grub config to parse
		return imagecustomizerapi.SELinuxModeDefault, false, nil
	}

	// Get the SELinux mode from the kernel command-line args.
	selinuxMode, err := getSELinuxModeFromLinuxArgs(args)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, false, err
	}

	return selinuxMode, true, nil
}

func (b *BootCustomizer) GetSELinuxMode(buildDir string, imageChroot safechroot.ChrootInterface) (imagecustomizerapi.SELinuxMode, error) {
	// Try to get the SELinux mode from grub configuration.
	selinuxMode, found, err := b.getSELinuxModeFromGrub()
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, err
	}
	if found && selinuxMode != imagecustomizerapi.SELinuxModeDefault {
		return selinuxMode, nil
	}

	// Fallback to extracting from UKI if grub config doesn't have SELinux settings.
	selinuxMode, found, err = b.getSELinuxModeFromUki(buildDir, imageChroot)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, fmt.Errorf("failed to extract SELinux mode from UKI:\n%w", err)
	}
	if found && selinuxMode != imagecustomizerapi.SELinuxModeDefault {
		return selinuxMode, nil
	}

	// Final fallback: Get the SELinux mode from the /etc/selinux/config file.
	selinuxMode, err = getSELinuxModeFromConfigFile(imageChroot)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, err
	}

	return selinuxMode, nil
}

// getSELinuxModeFromUki extracts SELinux mode from UKI kernel command-line arguments.
// Returns (mode, found, error) where:
//   - mode: The detected SELinux mode (or SELinuxModeDefault if not found)
//   - found: true if UKI files exist and were successfully parsed
//   - error: Any error encountered during extraction
func (b *BootCustomizer) getSELinuxModeFromUki(buildDir string, imageChroot safechroot.ChrootInterface) (imagecustomizerapi.SELinuxMode, bool, error) {
	espDir := filepath.Join(imageChroot.RootDir(), EspDir)
	tempDir := filepath.Join(buildDir, "uki-selinux-temp")

	err := os.MkdirAll(tempDir, 0o755)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, false, fmt.Errorf("failed to create temp directory: %w", err)
	}
	defer os.RemoveAll(tempDir)

	kernelToArgs, err := extractKernelCmdlineFromUkiEfis(espDir, tempDir)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, false, err
	}

	if len(kernelToArgs) == 0 {
		return imagecustomizerapi.SELinuxModeDefault, false, nil
	}

	args, err := parseFirstCmdlineFromUkiMap(kernelToArgs)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, false, err
	}

	// Extract SELinux mode from the parsed arguments
	selinuxMode, err := getSELinuxModeFromLinuxArgs(args)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, false, err
	}

	return selinuxMode, true, nil
}

// Update the image's SELinux kernel command-line args.
func (b *BootCustomizer) UpdateSELinuxCommandLine(selinuxMode imagecustomizerapi.SELinuxMode) error {
	newSELinuxArgs, err := selinuxModeToArgs(selinuxMode)
	if err != nil {
		return err
	}

	err = b.UpdateKernelCommandLineArgs(defaultGrubFileVarNameCmdlineForSELinux, selinuxArgNames, newSELinuxArgs)
	if err != nil {
		return err
	}

	return nil
}

// Update the image's SELinux kernel command-line args for OSModifier.
func (b *BootCustomizer) UpdateSELinuxCommandLineForEMU(selinuxMode imagecustomizerapi.SELinuxMode) error {
	newSELinuxArgs, err := selinuxModeToArgsWithPermissiveFlag(selinuxMode)
	if err != nil {
		return err
	}

	err = b.UpdateKernelCommandLineArgs(defaultGrubFileVarNameCmdlineForSELinux, selinuxArgNames, newSELinuxArgs)
	if err != nil {
		return err
	}

	return nil
}

func (b *BootCustomizer) UpdateKernelCommandLineArgs(defaultGrubFileVarName defaultGrubFileVarName,
	argsToRemove []string, newArgs []string,
) error {
	if b.bootConfigType == BootConfigTypeGrubMkconfig {
		defaultGrubFileContent, err := updateDefaultGrubFileKernelCommandLineArgs(b.defaultGrubFileContent,
			defaultGrubFileVarName, argsToRemove, newArgs)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent
	} else if b.bootConfigType == BootConfigTypeGrubLegacy {
		grubCfgContent, err := updateKernelCommandLineArgsAll(b.grubCfgContent, argsToRemove, newArgs)
		if err != nil {
			return err
		}

		b.grubCfgContent = grubCfgContent
	}
	// For UKI, kernel command-line args are embedded in the UKI itself

	return nil
}

// Makes changes to the /etc/default/grub file that are needed/useful for enabling verity.
func (b *BootCustomizer) PrepareForVerity() error {
	if b.bootConfigType == BootConfigTypeGrubMkconfig {
		// Force root command-line arg to be referenced by /dev path instead of by UUID.
		defaultGrubFileContent, err := UpdateDefaultGrubFileVariable(b.defaultGrubFileContent, "GRUB_DISABLE_UUID",
			"true")
		if err != nil {
			return err
		}

		// For rootfs verity, the root device will always be "/dev/mapper/root"
		rootDevicePath := imagecustomizerapi.VerityRootDevicePath
		defaultGrubFileContent, err = UpdateDefaultGrubFileVariable(defaultGrubFileContent, "GRUB_DEVICE",
			rootDevicePath)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent
	}
	// For UKI and grub-legacy, no preparation needed

	return nil
}

func (b *BootCustomizer) WriteToFile(imageChroot safechroot.ChrootInterface) error {
	if b.bootConfigType == BootConfigTypeGrubMkconfig {
		// Update /etc/default/grub file.
		err := WriteDefaultGrubFile(b.defaultGrubFileContent, imageChroot)
		if err != nil {
			return err
		}
		// Update /boot/grub2/grub.cfg file.
		err = installutils.CallGrubMkconfig(imageChroot)
		if err != nil {
			return fmt.Errorf("%w:\n%w", ErrBootGrubMkconfigGeneration, err)
		}
	} else if b.bootConfigType == BootConfigTypeGrubLegacy {
		// Update grub.cfg file.
		err := writeGrub2ConfigFile(b.grubCfgContent, imageChroot)
		if err != nil {
			return err
		}
	}
	// For UKI, boot configuration is in the UKI files themselves, not in grub config

	return nil
}

func (b *BootCustomizer) SetRootDevice(rootDevice string) error {
	updatedGrubFileContent, err := UpdateDefaultGrubFileVariable(b.defaultGrubFileContent, "GRUB_DEVICE", rootDevice)
	if err != nil {
		return err
	}

	b.defaultGrubFileContent = updatedGrubFileContent

	return nil
}
