// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package imagecustomizerlib

import (
	"errors"
	"fmt"
	"io/fs"

	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/imagecustomizerapi"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/imagegen/installutils"
	"github.com/microsoft/azure-linux-image-tools/toolkit/tools/internal/safechroot"
)

var (
	// Boot customization errors
	ErrBootGrubMkconfigGeneration        = NewImageCustomizerError("Boot:GrubMkconfigGeneration", "failed to generate grub.cfg via grub2-mkconfig")
	ErrBootNoConfigFound                 = NewImageCustomizerError("Boot:NoConfigFound", "no boot configuration found: grub.cfg does not exist and no UKI files found")
	ErrBootUkiPassthroughCmdlineModified = NewImageCustomizerError("Boot:UkiPassthroughCmdlineModified",
		"cannot modify kernel command-line in UKI passthrough mode: use 'mode: create' to customize kernel cmdline")
)

// bootConfigType represents the type of boot configuration used by the image.
type bootConfigType string

const (
	// bootConfigTypeGrubMkconfig indicates the image uses grub-mkconfig to generate grub.cfg.
	bootConfigTypeGrubMkconfig bootConfigType = "grub-mkconfig"
	// bootConfigTypeGrubLegacy indicates the image uses a manually maintained grub.cfg.
	bootConfigTypeGrubLegacy bootConfigType = "grub-legacy"
	// bootConfigTypeUki indicates the image uses UKI without grub.cfg.
	bootConfigTypeUki bootConfigType = "uki"
)

type BootCustomizer struct {
	// The contents of the /boot/grub2/grub.cfg file.
	grubCfgContent string

	// The contents of the /etc/default/grub file.
	defaultGrubFileContent string

	// The type of boot configuration used by the image.
	bootConfigType bootConfigType
}

func NewBootCustomizer(imageChroot safechroot.ChrootInterface) (*BootCustomizer, error) {
	grubCfgContent, err := ReadGrub2ConfigFile(imageChroot)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}

	defaultGrubFileContent, err := readDefaultGrubFile(imageChroot)
	if err != nil {
		return nil, err
	}

	// Determine boot configuration type
	bootConfigType, err := determineBootConfigType(grubCfgContent, imageChroot)
	if err != nil {
		return nil, err
	}

	b := &BootCustomizer{
		grubCfgContent:         grubCfgContent,
		defaultGrubFileContent: defaultGrubFileContent,
		bootConfigType:         bootConfigType,
	}
	return b, nil
}

func determineBootConfigType(grubCfgContent string, imageChroot safechroot.ChrootInterface) (bootConfigType, error) {
	// If grub.cfg doesn't exist, check for UKI
	if grubCfgContent == "" {
		hasUkis, err := baseImageHasUkis(imageChroot.(*safechroot.Chroot))
		if err == nil && hasUkis {
			// UKI images without grub.cfg are in passthrough mode (grub.cfg not regenerated)
			// For UKI create mode, grub.cfg is regenerated during kernel extraction, so it would exist
			return bootConfigTypeUki, nil
		}
		// No grub.cfg and no UKIs - this is an error
		return "", ErrBootNoConfigFound
	}

	// If grub.cfg exists, check if it's generated by grub-mkconfig
	if isGrubMkconfigConfig(grubCfgContent) {
		return bootConfigTypeGrubMkconfig, nil
	}

	return bootConfigTypeGrubLegacy, nil
}

// Inserts new kernel command-line args into the grub config file.
func (b *BootCustomizer) AddKernelCommandLine(extraCommandLine []string) error {
	if len(extraCommandLine) <= 0 {
		return nil
	}

	combinedArgs := GrubArgsToString(extraCommandLine)

	switch b.bootConfigType {
	case bootConfigTypeGrubMkconfig:
		defaultGrubFileContent, err := addExtraCommandLineToDefaultGrubFile(b.defaultGrubFileContent, combinedArgs)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent
	case bootConfigTypeGrubLegacy:
		// Add the args directly to the /boot/grub2/grub.cfg file.
		grubCfgContent, err := appendKernelCommandLineArgsAll(b.grubCfgContent, combinedArgs)
		if err != nil {
			return err
		}

		b.grubCfgContent = grubCfgContent

	case bootConfigTypeUki:
		// UKI passthrough mode: preserve existing UKI boot configuration.Expand commentComment on line R121ResolvedCode has comments. Press enter to view.
		// Cmdline args are embedded in UKI files and cannot be modified in passthrough mode.
		return ErrBootUkiPassthroughCmdlineModified
	}

	return nil
}

// Gets the image's configured SELinux mode.
func (b *BootCustomizer) getSELinuxModeFromGrub() (imagecustomizerapi.SELinuxMode, error) {
	var err error
	var args []grubConfigLinuxArg

	// Get the SELinux kernel command-line args.
	switch b.bootConfigType {
	case bootConfigTypeGrubMkconfig:
		// Check both GRUB_CMDLINE_LINUX and GRUB_CMDLINE_LINUX_DEFAULT variables
		// and merge arguments from both if they exist
		args, err = GetDefaultGrubFileLinuxArgsFromMultipleVars(b.defaultGrubFileContent)
		if err != nil {
			return imagecustomizerapi.SELinuxModeDefault, fmt.Errorf("failed to find SELinux args in grub file (%s):\n%w", installutils.GrubDefFile, err)
		}
	case bootConfigTypeGrubLegacy:
		args, _, err = getLinuxCommandLineArgs(b.grubCfgContent)
		if err != nil {
			return imagecustomizerapi.SELinuxModeDefault,
				fmt.Errorf("failed to parse SELinux args from grub file (%s):\n%w", installutils.GrubCfgFile, err)
		}

	// UKI passthrough mode case.
	case bootConfigTypeUki:
		return imagecustomizerapi.SELinuxModeDefault, nil
	}

	// Get the SELinux mode from the kernel command-line args.
	selinuxMode, err := getSELinuxModeFromLinuxArgs(args)
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, err
	}

	return selinuxMode, nil
}

func (b *BootCustomizer) GetSELinuxMode(imageChroot safechroot.ChrootInterface) (imagecustomizerapi.SELinuxMode, error) {
	// Get the SELinux mode from the kernel command-line args.
	selinuxMode, err := b.getSELinuxModeFromGrub()
	if err != nil {
		return imagecustomizerapi.SELinuxModeDefault, err
	}

	if selinuxMode == imagecustomizerapi.SELinuxModeDefault {
		// Get the SELinux mode from the /etc/selinux/config file.
		selinuxMode, err = getSELinuxModeFromConfigFile(imageChroot)
		if err != nil {
			return imagecustomizerapi.SELinuxModeDefault, err
		}
	}

	return selinuxMode, nil
}

// Update the image's SELinux kernel command-line args.
func (b *BootCustomizer) UpdateSELinuxCommandLine(selinuxMode imagecustomizerapi.SELinuxMode) error {
	newSELinuxArgs, err := selinuxModeToArgs(selinuxMode)
	if err != nil {
		return err
	}

	err = b.UpdateKernelCommandLineArgs(defaultGrubFileVarNameCmdlineForSELinux, selinuxArgNames, newSELinuxArgs)
	if err != nil {
		return err
	}

	return nil
}

// Update the image's SELinux kernel command-line args for OSModifier.
func (b *BootCustomizer) UpdateSELinuxCommandLineForEMU(selinuxMode imagecustomizerapi.SELinuxMode) error {
	newSELinuxArgs, err := selinuxModeToArgsWithPermissiveFlag(selinuxMode)
	if err != nil {
		return err
	}

	err = b.UpdateKernelCommandLineArgs(defaultGrubFileVarNameCmdlineForSELinux, selinuxArgNames, newSELinuxArgs)
	if err != nil {
		return err
	}

	return nil
}

func (b *BootCustomizer) UpdateKernelCommandLineArgs(defaultGrubFileVarName defaultGrubFileVarName,
	argsToRemove []string, newArgs []string,
) error {
	switch b.bootConfigType {
	case bootConfigTypeGrubMkconfig:
		defaultGrubFileContent, err := updateDefaultGrubFileKernelCommandLineArgs(b.defaultGrubFileContent,
			defaultGrubFileVarName, argsToRemove, newArgs)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent
	case bootConfigTypeGrubLegacy:
		grubCfgContent, err := updateKernelCommandLineArgsAll(b.grubCfgContent, argsToRemove, newArgs)
		if err != nil {
			return err
		}

		b.grubCfgContent = grubCfgContent
	case bootConfigTypeUki:
		// UKI passthrough mode: preserve existing UKI boot configuration.Expand commentComment on line R249ResolvedCode has comments. Press enter to view.
		// Cmdline args are embedded in UKI files and cannot be modified in passthrough mode.
		return ErrBootUkiPassthroughCmdlineModified
	}

	return nil
}

// Makes changes to the /etc/default/grub file that are needed/useful for enabling verity.
func (b *BootCustomizer) PrepareForVerity() error {
	switch b.bootConfigType {
	case bootConfigTypeGrubMkconfig:
		// Force root command-line arg to be referenced by /dev path instead of by UUID.
		defaultGrubFileContent, err := UpdateDefaultGrubFileVariable(b.defaultGrubFileContent, "GRUB_DISABLE_UUID",
			"true")
		if err != nil {
			return err
		}

		// For rootfs verity, the root device will always be "/dev/mapper/root"
		rootDevicePath := imagecustomizerapi.VerityRootDevicePath
		defaultGrubFileContent, err = UpdateDefaultGrubFileVariable(defaultGrubFileContent, "GRUB_DEVICE",
			rootDevicePath)
		if err != nil {
			return err
		}

		b.defaultGrubFileContent = defaultGrubFileContent

	case bootConfigTypeGrubLegacy:
		// Legacy grub configurations don't need special preparation for verity.
		// The verity args will be directly added to grub.cfg.

	case bootConfigTypeUki:
		// UKI passthrough mode: preserve existing UKI boot configuration.
		// Verity configuration is embedded in UKI files during UKI regeneration.
	}

	return nil
}

func (b *BootCustomizer) WriteToFile(imageChroot safechroot.ChrootInterface) error {
	switch b.bootConfigType {
	case bootConfigTypeGrubMkconfig:
		// Update /etc/default/grub file.
		err := WriteDefaultGrubFile(b.defaultGrubFileContent, imageChroot)
		if err != nil {
			return err
		}
		// Update /boot/grub2/grub.cfg file.
		err = installutils.CallGrubMkconfig(imageChroot)
		if err != nil {
			return fmt.Errorf("%w:\n%w", ErrBootGrubMkconfigGeneration, err)
		}
	case bootConfigTypeGrubLegacy:
		// Update grub.cfg file.
		err := writeGrub2ConfigFile(b.grubCfgContent, imageChroot)
		if err != nil {
			return err
		}
	case bootConfigTypeUki:
		// UKI passthrough mode: preserve existing UKI boot configuration.
		// UKI files are managed by UKI-specific customization logic, not through grub.
		// Future: May need to update boot loader configuration when native UKI boot support is added.
	}

	return nil
}

func (b *BootCustomizer) SetRootDevice(rootDevice string) error {
	updatedGrubFileContent, err := UpdateDefaultGrubFileVariable(b.defaultGrubFileContent, "GRUB_DEVICE", rootDevice)
	if err != nil {
		return err
	}

	b.defaultGrubFileContent = updatedGrubFileContent

	return nil
}
