# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Fork release branch

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/reuable/build-and-test.yml

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      # Create release branch and publish release.
      contents: write
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: out
        artifact-ids: version

    - name: Checkout
      uses: actions/checkout@v4

    - name: Fork release branch
      run: |
        VERSION=$(<"out/version/version.txt")
        MINOR_VERSION="$(grep -oP '^[0-9]+\.[0-9]+' <<< "$VERSION")"

        MINOR_VERSION_BRANCH="release/v${MINOR_VERSION}"
        git checkout -b "$MINOR_VERSION_BRANCH"
        git push

        TAG="v${VERSION}"
        git tag "$TAG"
        git push origin tag "$TAG"
