title: Azure Linux Image Tools
description: Documentation for Image Customizer & other image tools
theme: just-the-docs
exclude:
- Makefile
- Gemfile
- Gemfile.lock
- vendor
kramdown:
  gfm_quirks:
    # Don't convert `--` to em-dash.
  - no_auto_typographic

aux_links:
  "GitHub Repo":
    - "https://github.com/microsoft/azure-linux-image-tools"

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: "https://github.com/microsoft/azure-linux-image-tools"
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: tree
