title: Azure Linux Image Tools
description: Documentation for Image Customizer & other image tools
theme: just-the-docs
exclude:
- Makefile
- Gemfile
- Gemfile.lock
- vendor
kramdown:
  gfm_quirks:
    # Don't convert `--` to em-dash.
  - no_auto_typographic
