title: Azure Linux Image Tools
description: Documentation for Prism & other image tools
logo: /assets/images/logo.png
favicon_ico: "/assets/images/favicon.png"
theme: just-the-docs
exclude:
- Makefile
- Gemfile
- Gemfile.lock
- vendor
kramdown:
  gfm_quirks:
    # Don't convert `--` to em-dash.
  - no_auto_typographic
