# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build (preview)

permissions:
  contents: read
  # Azure login.
  id-token: write

on:
  push:
    branches:
    - release/*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: preview
      runFunctionalTests: true
      runVMTests: true
