# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: build & test

permissions:
  contents: read

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  dev:
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/reusable/build-and-test.yml
    with:
      publishType: dev

  main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable/build-and-test.yml
    with:
      publishType: main

  preview:
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/reusable/build-and-test.yml
    with:
      publishType: preview
