# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build (preview)

permissions: {}

on:
  push:
    branches:
    - release/*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Azure login.
      id-token: write
    with:
      publishType: preview
      runFunctionalTests: true
      runVMTests: true
