# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build (main)

permissions:
  contents: read

on:
  push:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: main
