# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build (dev)

permissions:
  contents: read
  # Report test results.
  actions: read
  checks: write

on:
  pull_request:
    branches:
    - main
    - release/*
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  # build:
  #  uses: ./.github/workflows/build.yml
  #  with:
  #    publishType: dev

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      runFunctionalTests: true
      runVMTests: true
