# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build (main)

permissions: {}

on:
  push:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Azure login.
      id-token: write
    with:
      publishType: main
      runFunctionalTests: true
      runVMTests: true
