name: Publish GitHub pages

permissions: {}

on:
  workflow_call: {}

jobs:
  deploy:
    name: Publish GitHub pages
    permissions:
      # GitHub pages publish.
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy to GitHub pages
      id: deployment
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
