# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build and publish preview release

permissions:
  contents: read
  # Publish to GHCR.
  packages: write

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: preview

  publish-container:
    uses: ./.github/workflows/publish-container.yml
    needs:
    - build
