# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Fork, build, test, and publish new minor version.

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml


  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      # Fork release branch and publish release.
      contents: write
    steps:
    # Fork release branch

    # Publish to GHCR

    # Publish GitHub release
