# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Release (preview)

permissions:
  contents: read
  # "Keyless" container signing
  id-token: write
  # Publish to GHCR.
  packages: write

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: preview
      runFunctionalTests: true

  publish-container:
    uses: ./.github/workflows/publish-container.yml
    needs:
    - build
