# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Release (preview)

permissions: {}

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: preview
      runFunctionalTests: true
      runVMTests: true
    permissions:
      contents: read
      # Azure login
      id-token: write

  publish-container:
    uses: ./.github/workflows/publish-container.yml
    needs:
    - build
    permissions:
      # "Keyless" container signing
      id-token: write
      # Publish to GHCR.
      packages: write
